#!/usr/bin/env python3
"""
AI 能力深度分析器
Author: Jim
Purpose: 从多维度分析用户的 AI 使用能力和协作模式
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from collections import defaultdict
import re
import logging

logger = logging.getLogger(__name__)


@dataclass
class AIProfile:
    """AI 能力画像"""
    # 核心能力评分 (0-100)
    prompt_engineering: int = 0          # 提示工程能力
    ai_product_design: int = 0           # AI 产品设计能力
    ai_service_integration: int = 0      # AI 服务集成能力
    human_ai_collaboration: int = 0      # 人机协作模式
    ai_workflow_design: int = 0          # AI 工作流设计
    
    # AI 使用模式
    ai_as_developer_tool: bool = False   # AI 作为开发工具
    ai_as_product_feature: bool = False  # AI 作为产品功能
    ai_as_thinking_partner: bool = False # AI 作为思维伙伴
    
    # 具体 AI 工具使用
    ai_tools_used: List[str] = field(default_factory=list)
    ai_apis_integrated: List[str] = field(default_factory=list)
    
    # 综合评估
    overall_ai_mastery: str = ""         # 综合 AI 掌握程度
    ai_philosophy: str = ""              # AI 协作哲学
    unique_strengths: List[str] = field(default_factory=list)
    
    # 能力雷达图数据
    radar_data: Dict[str, int] = field(default_factory=dict)


@dataclass  
class ProjectAIAnalysis:
    """单个项目的 AI 分析结果"""
    repo_name: str
    ai_involvement_level: str = 'none'   # 'none', 'light', 'moderate', 'heavy', 'core'
    ai_usage_types: List[str] = field(default_factory=list)
    ai_tools_detected: List[str] = field(default_factory=list)
    ai_patterns: List[str] = field(default_factory=list)
    evidence: List[str] = field(default_factory=list)


class AICapabilityAnalyzer:
    """AI 能力深度分析器"""
    
    def __init__(self):
        # AI 工具和服务识别
        self.ai_tools = {
            'claude': ['claude', 'anthropic', 'claude-3', 'sonnet', 'opus', 'haiku'],
            'openai': ['openai', 'gpt-4', 'gpt-3', 'chatgpt', 'davinci', 'turbo'],
            'copilot': ['copilot', 'github copilot'],
            'deepseek': ['deepseek', 'deep-seek'],
            'minimax': ['minimax', 'abab'],
            'gemini': ['gemini', 'bard', 'palm'],
            'local_llm': ['ollama', 'llama', 'mistral', 'qwen', 'lm-studio', 'lmstudio'],
        }
        
        self.ai_apis = {
            'openai_api': ['openai.api', 'openai.chat', 'ChatCompletion', 'openai.Client'],
            'anthropic_api': ['anthropic', 'claude.messages', 'Anthropic()'],
            'tts_services': ['tts', 'text-to-speech', 'speech synthesis', 'pyttsx', 'edge-tts', 'azure-tts'],
            'ocr_services': ['ocr', 'tesseract', 'paddleocr', 'easyocr', 'vision api'],
            'image_ai': ['stable-diffusion', 'dall-e', 'midjourney', 'image generation'],
            'embedding': ['embedding', 'vector', 'similarity', 'sentence-transformer'],
        }
        
        # AI 使用模式识别
        self.ai_patterns = {
            'prompt_engineering': [
                'prompt', 'system message', 'few-shot', 'chain of thought',
                'reasoning', 'instruction', 'template'
            ],
            'ai_code_generation': [
                'generated by', 'ai-assisted', 'copilot', 'claude code',
                'ai generated', 'auto-generated'
            ],
            'ai_product_integration': [
                'api integration', 'ai service', 'model inference',
                'completion', 'chat interface', 'ai response'
            ],
            'ai_workflow': [
                'pipeline', 'workflow', 'automation', 'batch processing',
                'multi-step', 'agent', 'chain'
            ],
            'human_ai_collab': [
                'review', 'validation', 'human-in-loop', 'feedback',
                'iteration', 'refinement'
            ]
        }
        
        # 项目类型与 AI 关联
        self.ai_project_indicators = {
            'ai_product': [
                'chatbot', 'assistant', 'ai-powered', 'intelligent',
                'smart', 'automated', 'bot', 'agent'
            ],
            'ml_data': [
                'model', 'training', 'dataset', 'prediction',
                'classification', 'regression', 'neural'
            ],
            'nlp': [
                'nlp', 'text analysis', 'sentiment', 'translation',
                'summarization', 'extraction'
            ],
            'vision': [
                'ocr', 'image recognition', 'object detection',
                'face', 'vision', 'cv'
            ],
            'audio': [
                'tts', 'stt', 'voice', 'audio', 'speech',
                'transcription', 'synthesis'
            ]
        }

    def analyze_project_ai_usage(self, repo_name: str, 
                                  readme_content: str,
                                  file_contents: Dict[str, str],
                                  dependencies: List[str],
                                  commit_messages: List[str] = None) -> ProjectAIAnalysis:
        """分析单个项目的 AI 使用情况"""
        
        analysis = ProjectAIAnalysis(repo_name=repo_name)
        
        # 合并所有文本进行分析
        all_text = f"{readme_content} {' '.join(file_contents.values())}".lower()
        dep_text = ' '.join(dependencies).lower()
        
        # 检测 AI 工具
        for tool_name, keywords in self.ai_tools.items():
            if any(kw in all_text or kw in dep_text for kw in keywords):
                analysis.ai_tools_detected.append(tool_name)
        
        # 检测 AI APIs
        for api_name, keywords in self.ai_apis.items():
            if any(kw.lower() in all_text or kw.lower() in dep_text for kw in keywords):
                analysis.ai_tools_detected.append(api_name)
        
        # 检测 AI 使用模式
        for pattern_name, keywords in self.ai_patterns.items():
            if any(kw in all_text for kw in keywords):
                analysis.ai_patterns.append(pattern_name)
        
        # 检测项目类型
        for proj_type, keywords in self.ai_project_indicators.items():
            if any(kw in all_text or kw in repo_name.lower() for kw in keywords):
                analysis.ai_usage_types.append(proj_type)
        
        # 分析 commit messages 中的 AI 痕迹
        if commit_messages:
            commit_text = ' '.join(commit_messages).lower()
            ai_commit_patterns = ['ai', 'gpt', 'claude', 'generated', 'auto', 'copilot']
            if any(p in commit_text for p in ai_commit_patterns):
                analysis.ai_patterns.append('ai_assisted_development')
        
        # 确定 AI 参与程度
        tool_count = len(analysis.ai_tools_detected)
        pattern_count = len(analysis.ai_patterns)
        type_count = len(analysis.ai_usage_types)
        
        total_score = tool_count * 2 + pattern_count + type_count
        
        if total_score == 0:
            analysis.ai_involvement_level = 'none'
        elif total_score <= 2:
            analysis.ai_involvement_level = 'light'
        elif total_score <= 5:
            analysis.ai_involvement_level = 'moderate'
        elif total_score <= 8:
            analysis.ai_involvement_level = 'heavy'
        else:
            analysis.ai_involvement_level = 'core'
        
        # 收集证据
        if 'openai' in analysis.ai_tools_detected or 'claude' in analysis.ai_tools_detected:
            analysis.evidence.append("集成了主流大语言模型 API")
        if 'tts_services' in analysis.ai_tools_detected:
            analysis.evidence.append("使用了 AI 语音合成技术")
        if 'ocr_services' in analysis.ai_tools_detected:
            analysis.evidence.append("集成了 AI 图像识别能力")
        if 'prompt_engineering' in analysis.ai_patterns:
            analysis.evidence.append("展现了提示工程能力")
        if 'ai_workflow' in analysis.ai_patterns:
            analysis.evidence.append("设计了 AI 工作流")
        
        return analysis

    def generate_ai_profile(self, project_analyses: List[ProjectAIAnalysis]) -> AIProfile:
        """从所有项目分析中生成 AI 能力画像"""
        
        profile = AIProfile()
        
        # 统计各维度
        all_tools = []
        all_patterns = []
        all_types = []
        involvement_scores = {'none': 0, 'light': 1, 'moderate': 2, 'heavy': 3, 'core': 4}
        
        total_involvement = 0
        ai_project_count = 0
        
        for analysis in project_analyses:
            all_tools.extend(analysis.ai_tools_detected)
            all_patterns.extend(analysis.ai_patterns)
            all_types.extend(analysis.ai_usage_types)
            
            score = involvement_scores.get(analysis.ai_involvement_level, 0)
            total_involvement += score
            if score > 0:
                ai_project_count += 1
        
        total_projects = len(project_analyses)
        
        # 计算各能力评分
        
        # 1. 提示工程能力
        prompt_indicators = all_patterns.count('prompt_engineering')
        profile.prompt_engineering = min(100, prompt_indicators * 20 + (40 if ai_project_count > 3 else 0))
        
        # 2. AI 产品设计能力
        product_indicators = len([t for t in all_types if t in ['ai_product', 'nlp', 'vision', 'audio']])
        profile.ai_product_design = min(100, product_indicators * 15 + (30 if ai_project_count > 5 else 0))
        
        # 3. AI 服务集成能力
        api_count = len([t for t in all_tools if 'api' in t.lower() or t in ['openai', 'claude', 'deepseek']])
        profile.ai_service_integration = min(100, api_count * 20 + (20 if ai_project_count > 2 else 0))
        
        # 4. 人机协作模式
        collab_indicators = all_patterns.count('human_ai_collab') + all_patterns.count('ai_assisted_development')
        profile.human_ai_collaboration = min(100, collab_indicators * 25 + (50 if ai_project_count > 5 else 0))
        
        # 5. AI 工作流设计
        workflow_indicators = all_patterns.count('ai_workflow')
        profile.ai_workflow_design = min(100, workflow_indicators * 30 + (30 if ai_project_count > 3 else 0))
        
        # 确定使用模式
        profile.ai_as_developer_tool = 'ai_code_generation' in all_patterns or 'ai_assisted_development' in all_patterns
        profile.ai_as_product_feature = any(t in all_types for t in ['ai_product', 'nlp', 'vision', 'audio'])
        profile.ai_as_thinking_partner = ai_project_count > total_projects * 0.5
        
        # 收集使用的工具
        profile.ai_tools_used = list(set([t for t in all_tools if not t.endswith('_api')]))
        profile.ai_apis_integrated = list(set([t for t in all_tools if t.endswith('_api') or t.endswith('_services')]))
        
        # 综合评估
        avg_score = (profile.prompt_engineering + profile.ai_product_design + 
                     profile.ai_service_integration + profile.human_ai_collaboration + 
                     profile.ai_workflow_design) / 5
        
        if avg_score >= 80:
            profile.overall_ai_mastery = "AI 协作大师"
        elif avg_score >= 60:
            profile.overall_ai_mastery = "AI 深度实践者"
        elif avg_score >= 40:
            profile.overall_ai_mastery = "AI 熟练使用者"
        elif avg_score >= 20:
            profile.overall_ai_mastery = "AI 积极探索者"
        else:
            profile.overall_ai_mastery = "AI 初步接触者"
        
        # 生成 AI 哲学描述
        profile.ai_philosophy = self._generate_ai_philosophy(profile, ai_project_count, total_projects)
        
        # 识别独特优势
        profile.unique_strengths = self._identify_strengths(profile, all_types, all_patterns)
        
        # 生成雷达图数据
        profile.radar_data = {
            '提示工程': profile.prompt_engineering,
            'AI产品设计': profile.ai_product_design,
            '服务集成': profile.ai_service_integration,
            '人机协作': profile.human_ai_collaboration,
            '工作流设计': profile.ai_workflow_design
        }
        
        return profile

    def _generate_ai_philosophy(self, profile: AIProfile, ai_count: int, total: int) -> str:
        """生成 AI 协作哲学描述"""
        
        ratio = ai_count / total if total > 0 else 0
        
        philosophies = []
        
        if ratio > 0.6:
            philosophies.append("AI 已成为创作过程中不可分割的协作伙伴")
        
        if profile.ai_as_product_feature and profile.ai_as_developer_tool:
            philosophies.append("既善于使用 AI 辅助开发，也擅长将 AI 融入产品")
        
        if profile.ai_service_integration > 70:
            philosophies.append("深谙将 AI 能力转化为可用服务的艺术")
        
        if profile.human_ai_collaboration > 60:
            philosophies.append("追求人与 AI 的协同增益，而非简单替代")
        
        if not philosophies:
            philosophies.append("在技术实践中积极探索 AI 的可能性")
        
        return "；".join(philosophies) + "。"

    def _identify_strengths(self, profile: AIProfile, 
                           types: List[str], 
                           patterns: List[str]) -> List[str]:
        """识别独特优势"""
        
        strengths = []
        
        # 基于类型分布
        type_counts = defaultdict(int)
        for t in types:
            type_counts[t] += 1
        
        if type_counts['audio'] > 2:
            strengths.append("语音 AI 应用专家")
        if type_counts['vision'] > 2:
            strengths.append("视觉 AI 应用专家")
        if type_counts['nlp'] > 2:
            strengths.append("自然语言处理专家")
        if type_counts['ai_product'] > 3:
            strengths.append("AI 产品创造者")
        
        # 基于模式分布
        if patterns.count('ai_workflow') > 2:
            strengths.append("AI 工作流架构师")
        if patterns.count('prompt_engineering') > 3:
            strengths.append("提示工程专家")
        
        # 基于工具多样性
        if len(profile.ai_tools_used) > 3:
            strengths.append("多元 AI 工具整合者")
        
        return strengths[:5]  # 最多返回5个优势


def analyze_ai_capabilities_from_repos(repos_data: List[Dict[str, Any]]) -> AIProfile:
    """便捷函数：从仓库数据分析 AI 能力"""
    
    analyzer = AICapabilityAnalyzer()
    project_analyses = []
    
    for repo in repos_data:
        analysis = analyzer.analyze_project_ai_usage(
            repo_name=repo.get('name', ''),
            readme_content=repo.get('readme_content', ''),
            file_contents=repo.get('file_contents', {}),
            dependencies=repo.get('dependencies', []),
            commit_messages=repo.get('commit_messages', [])
        )
        project_analyses.append(analysis)
    
    return analyzer.generate_ai_profile(project_analyses)
