version: '3.8'

services:
  github-monitor:
    build: .
    container_name: github-resume-monitor
    restart: unless-stopped
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config.json:/app/config.json
    networks:
      - monitor-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加Web界面服务
  web-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: github-monitor-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - API_BASE_URL=http://github-monitor:8000
    volumes:
      - ./data:/app/data:ro
    networks:
      - monitor-network
    depends_on:
      - github-monitor

networks:
  monitor-network:
    driver: bridge

volumes:
  monitor-data:
    driver: local
  monitor-logs:
    driver: local